---
swagger: "2.0"
info:
  description: "서울살이 API에 대한 RestAPI 명세서입니다."
  version: "1.0.0"
  title: "Seoul42 Server API"
  contact:
    email: "a28500312@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "virtserver.swaggerhub.com"
basePath: "/seoul42/Seoul42/1.0.0"
tags:
- name: "place"
  description: "해당 지역의 상권에 대한 정보"
- name: "house"
  description: "해당 주소에 대한 집 히스토리 정보"
schemes:
- "https"
paths:
  /place/search/infos:
    get:
      tags:
      - "place"
      summary: "search place"
      description: "좌표값을 입력받고, 입력받은 좌표값을 통해 해당 지역의 상권 정보를 얻는 api\n"
      operationId: "searchPlace"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "lat"
        in: "query"
        description: "해당 지역의 위도 값입니다"
        required: true
        type: "number"
        format: "latitude"
      - name: "lng"
        in: "query"
        description: "해당 지역의 경도 값입니다."
        required: true
        type: "number"
        format: "longitude"
      - name: "radius"
        in: "query"
        description: "얼마만큼의 범위를 정하는 값입니다."
        required: true
        type: "integer"
        maximum: 10000
        minimum: 0
        format: "distance"
      - name: "category"
        in: "query"
        description: "MT1  대형마트, CS2  편의점, PS3  어린이집, 유치원, SC4  학교, AC5  학원, PK6 \
          \ 주차장, OL7  주유소, 충전소, SW8  지하철역, BK9  은행, CT1  문화시설, AG2  중개업소, PO3  공공기\
          관, AT4  관광명소, AD5  숙박, FD6  음식점, CE7  카페, HP8  병원, PM9  약국"
        required: true
        type: "string"
        format: "category"
      responses:
        200:
          description: "주변 상권에 대한 정보 값이 있을 경우"
          schema:
            $ref: "#/definitions/PlaceResult"
        204:
          description: "주변 상권에 대한 정보 값이 없을 경우"
          schema:
            $ref: "#/definitions/PlaceInfoEmpty"
        400:
          description: "잘못된 통신"
          schema:
            $ref: "#/definitions/PlaceInfoFailure"
      x-swagger-router-controller: "Place"
  /house/search/info:
    get:
      tags:
      - "house"
      summary: "search house"
      description: "주소를 입력받고, 해당 주소에 대한 전월세에 관련한 히스토리를 볼 수 있는 api\n"
      operationId: "searchHouse"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "address"
        in: "query"
        description: "검색하려는 집의 주소입니다."
        required: true
        type: "string"
        format: "address"
      responses:
        200:
          description: "해당 집과 거래 내역이 있을 경우"
          schema:
            $ref: "#/definitions/HouseResult"
        204:
          description: "해당 집이 있지만, 거래 내역이 없거나 해당 집이 검색이 안 될 경우"
          schema:
            $ref: "#/definitions/HouseResultFailure"
        400:
          description: "잘못된 통신"
          schema:
            $ref: "#/definitions/PlaceResult"
      x-swagger-router-controller: "House"
definitions:
  PlaceResult:
    type: "object"
    required:
    - "address_name"
    - "category_group_name"
    - "distance"
    - "phone"
    - "place_name"
    - "place_url"
    - "road_address_name"
    - "x"
    - "y"
    properties:
      address_name:
        type: "string"
        format: "address"
        example: "서울 관악구 신림동 1422-38"
      category_group_name:
        type: "string"
        format: "category"
        example: "편의점"
      distance:
        type: "string"
        format: "distance"
        example: "327"
      phone:
        type: "string"
        format: "phone"
        example: "02-872-6665"
      place_name:
        type: "string"
        format: "title"
        example: "GS25 신림역점"
      place_url:
        type: "string"
        format: "url"
        example: "http://place.map.daum.net/12296239"
      road_address_name:
        type: "string"
        format: "address"
        example: "서울 관악구 남부순환로 1617"
      x:
        type: "string"
        format: "longitude"
        example: "126.930301346594"
      y:
        type: "string"
        format: "latitude"
        example: "37.484603540533"
    example:
      place_url: "http://place.map.daum.net/12296239"
      place_name: "GS25 신림역점"
      category_group_name: "편의점"
      road_address_name: "서울 관악구 남부순환로 1617"
      distance: "327"
      phone: "02-872-6665"
      x: "126.930301346594"
      y: "37.484603540533"
      address_name: "서울 관악구 신림동 1422-38"
  PlaceInfoEmpty:
    type: "object"
    required:
    - "place_result"
    - "status_code"
    properties:
      place_result:
        type: "string"
        example: ""
      status_code:
        type: "number"
        example: 204
  PlaceInfoFailure:
    type: "object"
    required:
    - "place_result"
    - "status_code"
    properties:
      place_result:
        type: "string"
        example: ""
      status_code:
        type: "number"
        example: 400
  HouseResult:
    required:
    - "address_result"
    - "address_status_code"
    - "house_rent_status_code"
    - "house_result"
    properties:
      address_result:
        $ref: "#/definitions/AddressResults"
      address_status_code:
        type: "number"
        format: "category"
        example: 200
      house_result:
        type: "array"
        items:
          $ref: "#/definitions/HousePriceResult"
      house_rent_status_code:
        type: "number"
        format: "phone"
        example: 200
    example:
      address_status_code: 200
      house_rent_status_code: 200
      address_result:
        building_name: "서울살이오피스텔"
        road_address_name: "서울 관악구 신림동1길 7000"
        x: "126.92850344579581"
        y: "37.48712889295937"
        address_name: "서울 관악구 신림동 1431-38"
      house_result:
      - RENT_AREA: "31"
        ROOM_CNT: "0"
        LAND_CD: "11620102001141237312"
        HOUSE_GBN_NM: "기타"
        RENT_CASE_NM: "준월세"
        CNTRCT_YEAR: "2015"
        RENT_GTN: "8000"
        CNTRCT_DE: "20151120"
        RENT_FEE: "460"
        RENT_CD: "3"
        DONG_NM: "1"
        BLDG_NM: "서울살이오피스텔"
        FLR_NO: "10"
        ACC_YEAR: "2015"
      - RENT_AREA: "31"
        ROOM_CNT: "0"
        LAND_CD: "11620102001141237312"
        HOUSE_GBN_NM: "기타"
        RENT_CASE_NM: "준월세"
        CNTRCT_YEAR: "2015"
        RENT_GTN: "8000"
        CNTRCT_DE: "20151120"
        RENT_FEE: "460"
        RENT_CD: "3"
        DONG_NM: "1"
        BLDG_NM: "서울살이오피스텔"
        FLR_NO: "10"
        ACC_YEAR: "2015"
  HouseResultFailure:
    required:
    - "address_result"
    - "address_status_code"
    - "house_rent_status_code"
    - "house_result"
    properties:
      address_result:
        type: "object"
        example: {}
        properties: {}
      address_status_code:
        type: "number"
        format: "category"
        example: 204
      house_result:
        type: "object"
        example:
        - {}
        properties: {}
      house_rent_status_code:
        type: "number"
        format: "phone"
        example: 204
  AddressResults:
    type: "object"
    required:
    - "address_name"
    - "building_name"
    - "road_address_name"
    - "x"
    - "y"
    properties:
      road_address_name:
        type: "string"
        format: "address"
        example: "서울 관악구 신림동1길 7000"
      building_name:
        type: "string"
        format: "title"
        example: "서울살이오피스텔"
      address_name:
        type: "string"
        format: "address"
        example: "서울 관악구 신림동 1431-38"
      x:
        type: "string"
        format: "latitude"
        example: "126.92850344579581"
      y:
        type: "string"
        format: "longitude"
        example: "37.48712889295937"
    example:
      building_name: "서울살이오피스텔"
      road_address_name: "서울 관악구 신림동1길 7000"
      x: "126.92850344579581"
      y: "37.48712889295937"
      address_name: "서울 관악구 신림동 1431-38"
  HousePriceResult:
    type: "object"
    required:
    - "ACC_YEAR"
    - "BLDG_NM"
    - "CNTRCT_DE"
    - "CNTRCT_YEAR"
    - "DONG_NM"
    - "FLR_NO"
    - "HOUSE_GBN_NM"
    - "LAND_CD"
    - "RENT_AREA"
    - "RENT_CASE_NM"
    - "RENT_CD"
    - "RENT_FEE"
    - "RENT_GTN"
    - "ROOM_CNT"
    properties:
      LAND_CD:
        type: "string"
        format: "uniqueid"
        example: "11620102001141237312"
      ACC_YEAR:
        type: "string"
        format: "year"
        example: "2015"
      BLDG_NM:
        type: "string"
        format: "title"
        example: "서울살이오피스텔"
      DONG_NM:
        type: "string"
        format: "dong"
        example: "1"
      FLR_NO:
        type: "string"
        format: "floor"
        example: "10"
      HOUSE_GBN_NM:
        type: "string"
        format: "house category"
        example: "기타"
      RENT_AREA:
        type: "string"
        format: "house size"
        example: "31"
      RENT_CD:
        type: "string"
        format: "전월세 구분 코드"
        example: "3"
      RENT_CASE_NM:
        type: "string"
        format: "전월세 구분"
        example: "준월세"
      RENT_GTN:
        type: "string"
        format: "보증금"
        example: "8000"
      RENT_FEE:
        type: "string"
        format: "월세"
        example: "460"
      CNTRCT_YEAR:
        type: "string"
        format: "계약년도"
        example: "2015"
      CNTRCT_DE:
        type: "string"
        format: "계약일자"
        example: "20151120"
      ROOM_CNT:
        type: "string"
        format: "방갯수"
        example: "0"
    example:
      RENT_AREA: "31"
      ROOM_CNT: "0"
      LAND_CD: "11620102001141237312"
      HOUSE_GBN_NM: "기타"
      RENT_CASE_NM: "준월세"
      CNTRCT_YEAR: "2015"
      RENT_GTN: "8000"
      CNTRCT_DE: "20151120"
      RENT_FEE: "460"
      RENT_CD: "3"
      DONG_NM: "1"
      BLDG_NM: "서울살이오피스텔"
      FLR_NO: "10"
      ACC_YEAR: "2015"
